apiVersion: skaffold/v2beta17
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
    tagPolicy: none
  artifacts:
    - image: kashiish19/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        network: host
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
