apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
    - image: kashiish19/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        network: host
  tagPolicy:
    sha256: {}
  local: {}

sync:
  manual:
    - dest: .
      src: 'src/**/*.ts'

defaultRepo: kashiish19/auth